trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: elfjes
      type: github
      endpoint: github
      name: elfjes/azure-pipeline-templates
      ref: refs/heads/elfjes

jobs:
- template: job--python-tox.yml@elfjes
  parameters:
    toxenvs: [pre-commit, py36, py37, py38]
    os: linux
    coverage: false

- template: job--pypi-release.yml@elfjes
  parameters:
    python: "3.8"
    distributions: "sdist bdist_wheel"
    externalFeed: pypi-gimme-that
    dependsOn:
      - tox_linux
